config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get 'my_portfolio', to:'users#my_portfolio'
  get 'search_stock', to:'stocks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks
    validates :name, :ticker, presence:true
    def self.new_lookup(ticker_symbol)
            publish = 'pk_890cffe62a60496f824f12575cf8b52a'
            secret = 'sk_457acbc9f6a8404297e83b49578bcbd1'
            client = IEX::Api::Client.new(
                publishable_token: publish,
                secret_token: secret,
                endpoint: 'https://cloud.iexapis.com/v1'
            )
            # client.quote(ticker_symbol).latest_price
            # p client.quote(ticker_symbol)
            begin
                obj = new(ticker:ticker_symbol, name:client.quote(ticker_symbol).company_name, last_price:client.quote(ticker_symbol).latest_price)
                return obj
            rescue=>exception
                return nil
            end
            
    end
    def self.checkStock(ticker_symbol)
        where(ticker:ticker_symbol).first
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            @stocks = current_user.stocks
            if @stock
                render 'users/my_portfolio'
            else
                flash[:alert]="Enter a valid symbol to search"
                redirect_to my_portfolio_path
            end
        else
            flash[:alert]="Please enter a symbol to search"
            redirect_to my_portfolio_path
        end
    end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
    def create 
        stock = Stock.checkStock(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        @user_stock = UserStock.create(user:current_user, stock: stock)
        flash[:notice]="Stock #{stock.name} was successfully added to your portfolio"
        redirect_to my_portfolio_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @stocks = current_user.stocks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to Finance Tracker</h1>

<%= button_to "Sign out", destroy_user_session_path, method: :delete %>

app/views/layouts/_messages.html.erb
<div class="container mt-4">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Finance-Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if !user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Signup", new_user_registration_path, class:"nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to current_user.email, '#', class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "My Portfolio", 'my_portfolio', class:"nav-link" %>
            </li>
            
            <li class="nav-item">
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link btn btn-primary text-light" %>
            </li>
            
        <%end%>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application"%>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-bordered table-hover mt-4">
        <thead>
            <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Latest Price</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @stocks.each do |stock| %>
                <tr>
                <th scope="row"><%= stock.ticker%></th>
                <td><%=stock.name%></td>
                <td><%=stock.last_price%></td>
                <td>Action Placeholder</td>
                </tr>
            <% end%>
        </tbody>
        </table>
    </div>
    </div>

app/views/users/_result.html.erb
<% if @stock %>
    <div class="card card-header mt-3" style="display:inline-block">
        <strong> Symbol: </strong><%=@stock.ticker%>
        <strong> Name: </strong><%=@stock.name%>
        <strong> Last Price: </strong><%=@stock.last_price%>
        <%= button_to 'Add to portfolio', user_stocks_path(user:current_user, ticker:@stock.ticker), class:'btn btn-success', method: :post %>
    </div>
<%end%>

app/views/users/my_portfolio.html.erb
<h1 class="mt-4">My Portfolio</h1>
<div class="search-area" style="padding-top:50px">   
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9" style="padding-right:0">
                <%= text_field_tag :stock, params[:stock], placeholder:'Stock ticker symbol', autofocus:true, class:"form-control form-control-lg" %>
            </div> 
            <div class="col-sm-3">
                <%= button_tag type: :submit, class:"btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <%end%>
            </div>    
        </div>
    <%end%>
</div>
<%= render 'users/result' %>
<% if !@stocks.empty?%>
    <%= render 'stocks/list' %>
<% end%>